export const Communities = [
  {
    communitie: "Vseti for android",
    category: "Technologies",
    id: 1,
    icon: require("../../assets/communities/icon_11.png"),
    fans: 66900,
  },
  {
    communitie: "Rock",
    category: "Music",
    id: 2,
    icon: require("../../assets/communities/rock.jpeg"),
    fans: 62200,
  },
  {
    communitie: "Photography",
    category: "Photo",
    id: 3,
    icon: require("../../assets/communities/photo.jpg"),
    fans: 59668,
  },
  {
    communitie: "Dogs",
    category: "Animal",
    id: 4,
    icon: require("../../assets/communities/dog.jpg"),
    fans: 50079,
  },
  {
    communitie: "Horror",
    category: "Films",
    id: 5,
    icon: require("../../assets/communities/horror.jpeg"),
    fans: 45670,
  },
  {
    communitie: "Travels",
    category: "Travels",
    id: 6,
    icon: require("../../assets/communities/travels.jpg"),
    fans: 40893,
  },
  {
    communitie: "Games",
    category: "Games",
    id: 7,
    icon: require("../../assets/communities/games.jpg"),
    fans: 36990,
  },
  {
    communitie: "MotoGP",
    category: "Moto",
    id: 8,
    icon: require("../../assets/communities/moto.jpg"),
    fans: 26999,
  },
  {
    communitie: "Books",
    category: "Literaturee",
    id: 9,
    icon: require("../../assets/communities/book.jpeg"),
    fans: 21557,
  },
].sort((a, b) => (a.fans > b.fans ? -1 : 1));
